spring:
  application:
    name: demo
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      javax:
        persistence:
          validation:
            group:
              pre-persist: com.kurly.jehui.validation.validation.SequentialValidationGroup
              pre-update: com.kurly.jehui.validation.validation.SequentialValidationGroup
    hibernate:
      ddl-auto: create